version: "3"
services: 
  golang:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    volumes: 
      - ./app:/app
    ports:
      - "8080:8080"
    tty: true

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./build/db/data:/var/lib/postgresql/data #データの永続化
      - ./build/db/init:/docker-entrypoint-initdb.d